controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_wrist_roll_joint
  - name: fake_right_gripper_controller
    joints:
      - r_index_joint
      - r_middle_joint
      - r_pinky_joint
      - r_ring_joint
      - r_thumb_joint