controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_out_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_wrist_roll_joint
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_out_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_wrist_roll_joint
  - name: fake_torso_controller
    joints:
      - waist_pan_joint
      - waist_roll_joint
  - name: fake_head_controller
    joints:
      - head_roll_joint
      - head_tilt_joint
      - head_pan_joint
  - name: fake_r_hand_controller
    joints:
      - r_wrist_roll_joint
      - r_index_joint
      - r_middle_joint
      - r_pinky_joint
      - r_ring_joint
      - r_thumb_joint
  - name: fake_l_hand_controller
    joints:
      - l_wrist_roll_joint
      - l_index_joint
      - l_middle_joint
      - l_pinky_joint
      - l_ring_joint
      - l_thumb_joint
  - name: fake_r_thumb_controller
    joints:
      - r_wrist_roll_joint
      - r_thumb_joint
  - name: fake_l_thumb_controller
    joints:
      - l_wrist_roll_joint
      - l_thumb_joint
  - name: fake_r_index_controller
    joints:
      - r_wrist_roll_joint
      - r_index_joint
  - name: fake_r_middle_controller
    joints:
      - r_wrist_roll_joint
      - r_middle_joint
  - name: fake_r_ring_controller
    joints:
      - r_wrist_roll_joint
      - r_ring_joint
  - name: fake_r_pinky_controller
    joints:
      - r_wrist_roll_joint
      - r_pinky_joint
  - name: fake_l_index_controller
    joints:
      - l_wrist_roll_joint
      - l_index_joint
  - name: fake_l_middle_controller
    joints:
      - l_wrist_roll_joint
      - l_middle_joint
  - name: fake_l_ring_controller
    joints:
      - l_wrist_roll_joint
      - l_ring_joint
  - name: fake_l_pinky_controller
    joints:
      - l_wrist_roll_joint
      - l_pinky_joint