# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  eyes_pan_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.5
    min_position: -1.5
  eyes_tilt_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.5
    min_position: -1.5
  head_pan_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.5
    min_position: -1.5
  head_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0
    min_position: 0
  head_tilt_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1
    min_position: -1
  jaw_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1
    min_position: 0
  l_elbow_flex_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_eye_pan_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_index1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_index3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_index_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_middle1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_middle3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_middle_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_pinky1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_pinky3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_pinky4_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_pinky_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_ring1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_ring3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_ring4_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_ring_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_shoulder_lift_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_shoulder_out_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_thumb1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_thumb3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_thumb_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_upper_arm_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  l_wrist_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_elbow_flex_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_index1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_index3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_index_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_middle1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_middle3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_middle_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_pinky1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_pinky3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_pinky4_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_pinky_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_ring1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_ring3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_ring4_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_ring_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_shoulder_lift_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_shoulder_out_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_thumb1_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_thumb3_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_thumb_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_upper_arm_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  r_wrist_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -3.14
  waist_pan_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1
    min_position: -1
  waist_roll_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1
    min_position: -1